ERROR_USER_NOT_FOUND = "\nError: User not found.\n"
ERROR_NO_USERS_FOUND = "\nError: No Users Found.\n"
ERROR_CAR_NOT_FOUND = "\nError: Car not found.\n"
ERROR_NO_CARS_FOUND = "\nError: No Cars Found.\n"
ERROR_SERVICE_NOT_FOUND = "\nError: Service not found.\n"
ERROR_NO_SERVICES_FOUND = "\nError: No Services Found.\n"
PRESS_ENTER_TO_GO_BACK = "\nPress Enter to go back to the Menu.\n"